"use strict";
window.addEventListener("DOMContentLoaded", init);

// INIT
function init() {
  console.log("init");
}

//GET FUNCTION PRODUCT  DATA EITHER FROM DATABASE OR DIRECTLY FROM INPUT FX ITEM AMOUNT 1,2,3 VOLT CHARGERS

//DISPLAY PRODUCTS -- IF WE USE DATABSE !!

//EVENTLISTENER CLICK GOES TO PURCHASE FLOW HTML THOUGH URL AND BRINGS DATA = AMOUNT OF ITEMS AND IF SHIPPING IS REQUIRED

//SOME CODE THAT TJEKS FOR VALIDATION AND TAKE ACTION ACORDINGLY

// PUTS AMOUNT DATA INTO DATA OBJECT WITH PERSONAL INFORMATION

// OBEJCT OF DATA STUCTURE TO BE SEND INTO POST DATA (NEEDS TO MATCH restdb.io )

//EVENT LISTENER CLICK ON SUBMIT
//POST FUNCTION PERSONAL  / PRODUCT DATA

//SOME CODE THAT CHANGES FORM SECITON 1-2

//SOME CODE THAT CREATE HOVER/MOUSEOVER WINDOW ON INFORMATION ICONS
// SOME CODE THAT TJEKS WICH INFORMATION ICON IS TARGET
// SOME CODE THAT DISLPAY MODAL WIDTH INFORMATION ACORDING TO TARGET ID

// SOME POP UP SIGN SAYING ITS NOT AN OFICIAL SITE
